spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
#      default-filters:
#        - name: AuthorizationHeaderFilter
#          args:
#            baseMessage: Spring Cloud Gateway Filter
#            preLogger: true
#            postLogger: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "https://domaincom:8080"
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#              - OPTIONS
#              - DELETE
#              - PATCH
#            allowedHeaders: '*'
#            allow-credentials: true
      routes: #라우팅에 대한 정보

        - id: user-login-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/login
            - Method=POST
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user-logout-service
          uri: lb://USER-SERVICE
          predicates:
            - Method=POST
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user-service #해당 라우팅이 어떠한 이름으로 라우팅 될 것인지에 대한 이름
          uri: lb://USER-SERVICE #현재 라우팅을 어디에 포워딩 시킬 것인지를 명시해준다.
          predicates: #조건식으로 특정 요청이 predicates에 맞는 조건으로 들어오면 해당 route를 수행할 것을 지정한다.
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board/**
          filters:
            - RewritePath=/board/(?<path>.*),/$\{path}
            - AuthorizationHeaderFilter

server:
  port: 8889

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1 #하트비트 인터벌
    lease-expiration-duration-in-seconds: 2 # 디스커버리는 서비스 등록 해제 하기 전에 마지막 하트비트에서부터 2초 기다림
    # instance부분의 위에 2개 설정은 해당 서비스가 종료되면 디스커버리에 바로 삭제 되게 해주는 옵션으로 개발단계에서 편의성을 위해 넣었다.
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: $2a$10$q42lY7Y18xqrFt1qbODZIO4OMTeOxnrCe7tF3n9bazJinVE7VH5Pi
  refresh-token-name: refresh-token
  access-token-name: access-token